name: 'Release notification bot Example'
on:
  workflow_dispatch:

jobs:
  Sent-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: post a message to slack
        uses: ./
        with:
          compareURL: ${{ secrets.COMPARE_URL }}
          projectNames: ${{ secrets.PROJECT_NAMES }}
          slackWebhook: ${{ secrets.INCOMING_WEBHOOK_URL }}
          repository: ${{ secrets.REPOSITORY }}
          authToken: ${{ secrets.AUTH_TOKEN }}
          jiraURL: ${{ secrets.JIRA_URL }}
          repositoryKind: 'private'
